[workspace]
resolver = "2"
members = ["tributary-fs", "tributary-proto"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
repository = "https://github.com/al8n/tributaries"
homepage = "https://github.com/al8n/tributaries"

[workspace.dependencies]

[workspace.lints.rust]
rust_2018_idioms = "warn"
single_use_lifetimes = "warn"
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(all_tests)',
  'cfg(tarpaulin)',
] }
